#%RAML 1.0

title: Anidub API
mediaType: application/json
version: v1
baseUri: http://anidub-api.herokuapp.com/method

types:
  fav_basic_struct:
    type: object
    properties:
      id:
        type: integer
        description: "ID тайтла"
      user_id:
        type: integer
        description: "ID пользователя"
      password:
        type: string
        description: "Пароль в формате md5"
  fav_count_struct:
    type: object
    properties:
      user_id:
        type: integer
        description: "ID пользователя"
      password:
        type: string
        description: "Пароль в формате md5"
  fav_list_struct:
    type: object
    properties:
      user_id:
        type: integer
        description: "ID пользователя"
      password:
        type: string
        description: "Пароль в формате md5"
      page:
        type: integer
        description: "Страница в закладках"
  Account_login_struct:
    type: object
    properties:
      login:
        type: string
        description: "Логин пользователя"
      password:
        type: string
        description: "Пароль пользоватля в формате md5"
  Get_Episode_struct:
    type: object
    properties:
      id:
        type: integer
        description: "ID тайтла у которого надо получить серии"
  Super_Search_struct:
    type: object
    properties:
      genres:
        type: integer
        description: "ID жанра"
      dubbers:
        type: integer
        description: "ID дабера"
      year:
        type: integer
        description: "Год выхода"
      studio:
        type: integer
        description: "ID студии"
      sort:
        type: integer
        description: ""
      cat:
        type: integer
        description: ""
      series:
        type: integer
        description: "Количество серий"
      page:
        type: integer
        description: "Страница"
  Search_struct:
    type: object
    properties:
      query:
        type: string
        description: "Строка с названием"
      page:
        type: integer
        description: "Страница поиска)))"

  Page_struct:
    type: object
    properties:
      page:
        type: integer
        description: "Номер страницы"
  ID_Info_struct:
    type: object
    properties:
      id:
        type: integer
        description: "ID тайтла "
  TitleList:
    type: object
    properties:
      Error: boolean
      Response:
        type: object
        properties:
          Code: integer
          Message: string
          Data:
            type: object
            properties:
              ID: integer
              Url: string
              Title:
                type: object
                properties:
                  Full: string
                  Russian: string
                  Original: string
                  Episodes: string
              Uploder: string
              Categories: array
              Poster: string
              Information:
                type: object
                properties:
                  Year: integer
                  Genres: string
                  Country: string
                  Episodes: integer
                  Release: string
                  Director: string
                  Author: string
                  Dubbers: string
                  Translators: string
                  Studio: string
                  Description: string
              Commentaries: integer
              Rating:
                type: object
                properties:
                  Type: integer
                  Grade: string
                  Votes: string
  TitleInfo:
    type: object
  fav_delete_response:
    type: object
    properties:
      Error: boolean
      Response:
        type: object
        properties:
          Code: integer
          Message: string
          Data: string
  account_login_response:
    type: object
    properties:
      Error: boolean
      Response:
        type: object
        properties:
          Code: integer
          Message: string
          Data:
            type: object
            properties:
              ID: string
  fav_isFav_response:
    type: object
    properties:
      Error: boolean
      Response:
        type: object
        properties:
          Code: integer
          Message: string
          Data: boolean
  titles_getEpisodes_response:
    type: object
    properties:
      Error: boolean
      Response:
        type: object
        properties:
          Code: integer
          Message: string
          Data:
            type: object
            properties:
                Mirror:
                  type: array
                  items:
                    type: object
                    properties:
                      Name: string
                      Url: string
                Anidub:
                  type: array
                  items:
                    type: object
                    properties:
                      Name: string
                      Url: string

/titles.list:
  displayName: "Получить список тайтлов со страницы сайта"
  description: "Получить список тайтлов со страницы сайта"

  post:
    displayName: "Получить список тайтлов со страницы сайта"
    description: "Получить список тайтлов со страницы сайта"

    body:
      application/json:
        type: Page_struct
        example: |
          {
          "page":1
          }
    responses:
      200:
       body:
        application/json:
          example: |
              {
              "Error": false,
              "Response": {
              "Code": 200,
              "Message": "Success.",
              "Data": [
              {
              "ID": "10059",
              "Url": "http://online.anidub.com/anime_tv/anime_ongoing/10059-vkusnyatina-po-italyanski-piace-watashi-no-italian-01-iz-12.html",
              "Title": {
              "Full": "Вкуснятина по-итальянски / Piace: Watashi no Italian [11 из 12]",
              "Russian": "Вкуснятина по-итальянски",
              "Original": "Piace: Watashi no Italian",
              "Episodes": "[11 из 12]"
              },
              "Uploader": "Planokyr128",
              "Categories": [
              "Аниме TV Онлайн",
              "Аниме Ongoing Онлайн"
              ],
              "Poster": "http://static3.anidub.com/online/poster/26bb3e2e4b.jpg",
              "Information": {
                "Year": "2017",
                "Genres": "комедия, повседневность",
                "Country": "Япония",
                "Episodes": "12",
                "Release": "c 11.01.2017",
                "Director": "Сакурай Хироаки",
                "Author": "Ватанабэ Ацуко",
                "Dubbers": "Lonely Dragon, Oni",
                "Translators": "Oni",
                "Studio": "Zero-G",
                "Description": "Моринэ Насаке - учащаяся средней школы, устраивается на работу в итальянский ресторан Trattoria Festa, наполненный различными причудливыми персонажами"
                },
                "Commentaries": "19",
                "Rating": {
                  "Type": 0,
                  "Grade": "93%",
                  "Votes": ""
                }
                }
                ]
                }
                }
/titles.info:
    displayName: "Получить иноформацию об тайтлов по ID"
    description: "Получить иноформацию об тайтлов по ID"
    post:
      displayName: "Получить иноформацию об тайтлов по ID"
      description: "Получить иноформацию об тайтлов по ID"
      body:
        application/json:
          type: ID_Info_struct
          example: |
            {
            "id":10059
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "Error": false,
                  "Response": {
                    "Code": 200,
                    "Message": "Success.",
                    "Data": {
                      "ID": "10059",
                      "Url": "http://online.anidub.com/anime_tv/anime_ongoing/10059-vkusnyatina-po-italyanski-piace-watashi-no-italian-01-iz-12.html",
                      "Title": {
                        "Full": "Вкуснятина по-итальянски / Piace: Watashi no Italian [11 из 12]",
                        "Russian": "Вкуснятина по-итальянски",
                        "Original": "Piace: Watashi no Italian",
                        "Episodes": "[11 из 12]"
                      },
                      "Uploader": "Planokyr128",
                      "Categories": [
                        "Аниме TV Онлайн",
                        "Аниме Ongoing Онлайн"
                      ],
                      "Poster": "http://static3.anidub.com/online/poster/26bb3e2e4b.jpg",
                      "Information": {
                        "Year": "2017",
                        "Genres": "комедия, повседневность",
                        "Country": "Япония",
                        "Episodes": "12",
                        "Release": "c 11.01.2017",
                        "Director": "Сакурай Хироаки",
                        "Author": "Ватанабэ Ацуко",
                        "Dubbers": "Lonely Dragon, Oni",
                        "Translators": "Fraksinus",
                        "Studio": "Zero-G",
                        "Description": "Моринэ Насаке - учащаяся средней школы, устраивается на работу в итальянский ресторан Trattoria Festa, наполненный различными причудливыми персонажами"
                      },
                      "Comments": {
                        "Count": "19",
                        "Best": [
                          {
                            "Author": "Khariton444",
                            "Avatar": "http://online.anidub.com/uploads/fotos/foto_304435.jpg",
                            "Content": "во всех аниме где показывают еду у меня дико текут слюни))"
                          }
                        ]
                      },
                      "Rating": {
                        "Type": 0,
                        "Grade": "93%",
                        "Votes": ""
                      },
                      "Episodes": {
                        "Mirror": [
                          {
                            "Name": "Вкуснятина по-итальянски - 1 серия Lonely Dragon, Oni",
                            "Url": "http://video.sibnet.ru/shell.php?videoid=2810230"
                          }
                        ]
                      },
                      "Timeline": [],
                      "Questions": []
                    }
                  }
                }
/titles.search:
  displayName: "Поиск тайтлов по названию"
  description: "Поиск тайтлов по названию"
  post:
    displayName: "Поиск тайтлов по названию"
    description: "Поиск тайтлов по названию"
    body:
      application/json:
        type: Search_struct
        example: |
            {
            "query": "Наруто",
            "page": 0
            }
    responses:
      200:
        body:
          application/json:
            example: |
              {
              "Error": false,
              "Response": {
              "Code": 200,
              "Message": "Success.",
              "Data": [
              {
              "ID": "10059",
              "Url": "http://online.anidub.com/anime_tv/anime_ongoing/10059-vkusnyatina-po-italyanski-piace-watashi-no-italian-01-iz-12.html",
              "Title": {
              "Full": "Вкуснятина по-итальянски / Piace: Watashi no Italian [11 из 12]",
              "Russian": "Вкуснятина по-итальянски",
              "Original": "Piace: Watashi no Italian",
              "Episodes": "[11 из 12]"
              },
              "Uploader": "Planokyr128",
              "Categories": [
              "Аниме TV Онлайн",
              "Аниме Ongoing Онлайн"
              ],
              "Poster": "http://static3.anidub.com/online/poster/26bb3e2e4b.jpg",
              "Information": {
                "Year": "2017",
                "Genres": "комедия, повседневность",
                "Country": "Япония",
                "Episodes": "12",
                "Release": "c 11.01.2017",
                "Director": "Сакурай Хироаки",
                "Author": "Ватанабэ Ацуко",
                "Dubbers": "Lonely Dragon, Oni",
                "Translators": "Oni",
                "Studio": "Zero-G",
                "Description": "Моринэ Насаке - учащаяся средней школы, устраивается на работу в итальянский ресторан Trattoria Festa, наполненный различными причудливыми персонажами"
                },
                "Commentaries": "19",
                "Rating": {
                  "Type": 0,
                  "Grade": "93%",
                  "Votes": ""
                }
                }
                ]
                }
                }
/titles.sf:
  displayName: "Расширеный поиск с использованием параметров"
  description: "Расширеный поиск с использованием параметров"
  post:
    displayName: "Расширеный поиск с использованием параметров"
    description: "Расширеный поиск с использованием параметров"
    body:
      application/json:
        type: Super_Search_struct
        example: |
          {
          "genres":1,
          "dubbers":1,
          "year":2016,
          "studio":1,
          "sort":1,
          "cat":1,
          "series":12,
          "page":1
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
              "Error": false,
              "Response": {
              "Code": 200,
              "Message": "Success.",
              "Data": [
              {
              "ID": "10059",
              "Url": "http://online.anidub.com/anime_tv/anime_ongoing/10059-vkusnyatina-po-italyanski-piace-watashi-no-italian-01-iz-12.html",
              "Title": {
              "Full": "Вкуснятина по-итальянски / Piace: Watashi no Italian [11 из 12]",
              "Russian": "Вкуснятина по-итальянски",
              "Original": "Piace: Watashi no Italian",
              "Episodes": "[11 из 12]"
              },
              "Uploader": "Planokyr128",
              "Categories": [
              "Аниме TV Онлайн",
              "Аниме Ongoing Онлайн"
              ],
              "Poster": "http://static3.anidub.com/online/poster/26bb3e2e4b.jpg",
              "Information": {
                "Year": "2017",
                "Genres": "комедия, повседневность",
                "Country": "Япония",
                "Episodes": "12",
                "Release": "c 11.01.2017",
                "Director": "Сакурай Хироаки",
                "Author": "Ватанабэ Ацуко",
                "Dubbers": "Lonely Dragon, Oni",
                "Translators": "Oni",
                "Studio": "Zero-G",
                "Description": "Моринэ Насаке - учащаяся средней школы, устраивается на работу в итальянский ресторан Trattoria Festa, наполненный различными причудливыми персонажами"
                },
                "Commentaries": "19",
                "Rating": {
                  "Type": 0,
                  "Grade": "93%",
                  "Votes": ""
                }
                }
                ]
                }
                }
/titles.getEpisodes:
  displayName: "Полученить список серий тайтла по ID"
  description: "Полученить список серий тайтла по ID"
  post:
    displayName: "Полученить список серий тайтла по ID"
    description: "Полученить список серий тайтла по ID"
    body:
      application/json:
        type: Get_Episode_struct
        example: |
          {
            "id":10059
          }
    responses:
      200:
        body:
          application/json:
            type: titles_getEpisodes_response
            example: |
              {
              "Error": false,
              "Response": {
                "Code": 200,
                "Message": "Success.",
                "Data": {
                  "Mirror": [
                  {
                  "Name": "Вкуснятина по-итальянски - 1 серия Lonely Dragon, Oni",
                  "Url": "http://video.sibnet.ru/shell.php?videoid=2810230"
                  }],
                  "Anidub": [
                  {
                  "Name": "Вкуснятина по-итальянски - 1 серия Lonely Dragon, Oni",
                  "Url": "http://player.adcdn.tv/embed/storage4/2715/1//0JLQutGD0YHQvdGP0YLQuNC90LAg0L%2FQvi3QuNGC0LDQu9GM0Y%2FQvdGB0LrQuCAtIDEg0YHQtdGA0LjRjyBMb25lbHkgRHJhZ29uLCBPbmk%3D/kvv"
                  }]
                }
              }
              }
/account.login:
  displayName: "Авторизация на сайте"
  description: "Авторизация на сайте"
  post:
    displayName: "Авторизация на сайте"
    description: "Авторизация на сайте"
    body:
      application/json:
        type: Account_login_struct
        example: |
          {
          "login": "thetaiiok",
          "password": "5c49ee4ee4705b81da5cb466c3a76eda"
          }
    responses:
      200:
        body:
          application/json:
            type: account_login_response
            example: |
              {
              "Error": false,
              "Response": {
                "Code": 200,
                "Message": "Success.",
                "Data": {
                  "ID": "867671"
                }
              }
              }
/fav.list:
  displayName: "Получить список тайтлов в закладках по странице"
  description: "Получить список тайтлов в закладках по странице"
  post:
    displayName: "Получить список тайтлов в закладках по странице"
    description: "Получить список тайтлов в закладках по странице"
    body:
      application/json:
        type: fav_list_struct
        example: |
          {
          "user_id": 867671,
          "password": "5c49ee4ee4705b81da5cb466c3a76eda",
          "page": 1
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
              "Error": false,
              "Response": {
              "Code": 200,
              "Message": "Success.",
              "Data": [
              {
              "ID": "10059",
              "Url": "http://online.anidub.com/anime_tv/anime_ongoing/10059-vkusnyatina-po-italyanski-piace-watashi-no-italian-01-iz-12.html",
              "Title": {
              "Full": "Вкуснятина по-итальянски / Piace: Watashi no Italian [11 из 12]",
              "Russian": "Вкуснятина по-итальянски",
              "Original": "Piace: Watashi no Italian",
              "Episodes": "[11 из 12]"
              },
              "Uploader": "Planokyr128",
              "Categories": [
              "Аниме TV Онлайн",
              "Аниме Ongoing Онлайн"
              ],
              "Poster": "http://static3.anidub.com/online/poster/26bb3e2e4b.jpg",
              "Information": {
                "Year": "2017",
                "Genres": "комедия, повседневность",
                "Country": "Япония",
                "Episodes": "12",
                "Release": "c 11.01.2017",
                "Director": "Сакурай Хироаки",
                "Author": "Ватанабэ Ацуко",
                "Dubbers": "Lonely Dragon, Oni",
                "Translators": "Oni",
                "Studio": "Zero-G",
                "Description": "Моринэ Насаке - учащаяся средней школы, устраивается на работу в итальянский ресторан Trattoria Festa, наполненный различными причудливыми персонажами"
                },
                "Commentaries": "19",
                "Rating": {
                  "Type": 0,
                  "Grade": "93%",
                  "Votes": ""
                }
                }
                ]
                }
                }
/fav.count:
  displayName: "Получить количество тайтлов в закладках"
  description: "Получить количество тайтлов в закладках"
  post:
    displayName: "Получить количество тайтлов в закладках"
    description: "Получить количество тайтлов в закладках"
    body:
      application/json:
        type: fav_count_struct
        example: |
          {
          "user_id": 867671,
          "password": "5c49ee4ee4705b81da5cb466c3a76eda"
          }
    responses:
      200:
        body:
          application/json:
            type: fav_delete_response
            example: |
              {
              "Error": false,
              "Response": {
                "Code": 200,
                "Message": "Success.",
                "Data": "1"
              }
              }
/fav.isFav:
  displayName: "Узнать содержится ли тайтл в закладках"
  description: "Узнать содержится ли тайтл в закладках"
  post:
    displayName: "Узнать содержится ли тайтл в закладках"
    description: "Узнать содержится ли тайтл в закладках"
    body:
      application/json:
        type: fav_basic_struct
        example: |
          {
          "id": 10125,
          "user_id": 867671,
          "password": "5c49ee4ee4705b81da5cb466c3a76eda"
          }
    responses:
      200:
        body:
          application/json:
            type: fav_isFav_response
            example: |
              {
              "Error":false,
              "Response":{
                "Code":200,
                "Message":"Success.",
                "Data":false
                }
              }
/fav.add:
  displayName: "Добавить тайтл в закладки"
  description: "Добавить тайтл в закладки"
  post:
    displayName: "Добавить тайтл в закладки"
    description: "Добавить тайтл в закладки"
    body:
      application/json:
        type: fav_basic_struct
        example: |
          {
          "id": 10125,
          "user_id": 867671,
          "password": "5c49ee4ee4705b81da5cb466c3a76eda"
          }
    responses:
      200:
        body:
          application/json:
            type: fav_delete_response
            example: |
              {
              "Error": false,
              "Response": {
                "Code": 200,
                "Message": "Success.",
                "Data": "Added"
              }
              }
/fav.delete:
  displayName: "Удалить тайтл из закладок"
  description: "Удалить тайтл из закладок"
  post:
    displayName: "Удалить тайтл из закладок"
    description: "Удалить тайтл из закладок"
    body:
      application/json:
        type: fav_basic_struct
        example: |
          {
          "id": 10125,
          "user_id": 867671,
          "password": "5c49ee4ee4705b81da5cb466c3a76eda"
          }
    responses:
      200:
        body:
          application/json:
            type: fav_delete_response
            example: |
              {
              "Error": false,
              "Response": {
                "Code": 200,
                "Message": "Success.",
                "Data": "Removed"
              }
              }
